### ISSUE TITLE
Fix circular import

### ISSUE THREAD

**Issue by iangow** [iangow/skeleton#1]
```
Python 3.8.2 (default, Feb 27 2020, 19:58:50) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skeleton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/skeleton/__init__.py", line 4, in <module>
    from skeleton import some_bones
ImportError: cannot import name 'some_bones' from partially initialized module 'skeleton' (most likely due to a circular import) (/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/skeleton/__init__.py)
>>> 
```

**Comment by iangow** [comment]
*Finally!* Got it.

```
igowmbp15:~ igow$ python3
Python 3.8.2 (default, Feb 27 2020, 19:58:50) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from skeleton import some_bones
>>> some_bones()
3.14159265358979
>>> 
```
